# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_manager', '0014_auto_20170518_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackappointmentmap',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktype',
            name='name',
            field=models.CharField(choices=[('prior results', 'Results'), ('appointment', 'Appointment'), ('review', 'Take a Review'), ('future courses', 'Available courses')], max_length=48, unique=True),
        ),
    ]
